---
title: "STAT 656: Project "
subtitle: ""
author: "James Li"
date: "3/19/2021"
output: html_document
---

```{r setup, include=FALSE,message=FALSE, warning=FALSE}
require(dplyr)
require(caret)
require(quantmod)
require(tidyverse)
require(tidyquant)
require(dwt)
require(dtwclust)

rm(list=ls())
```


First we must get our data. We will look at the logarithmic returns for stocks in the S&P500 over the two year period ranging from January 1, 2019 to December 31, 2020.

```{r import_data, cache=TRUE}
returns <- tq_index('DOW') %>%
  tq_get(from='2017-01-01', to='2021-02-28', verbose=T) %>%
  group_by(symbol) %>%
  tq_transmute(select=adjusted, mutate_fun=periodReturn, period='daily', type='log', col_rename='log_daily_returns') %>%
  pivot_wider(names_from=date, values_from=log_daily_returns) %>%
  ungroup %>%
  drop_na
```
```{r}
if(exists("returns")) {
save(returns,file="dow-4year.RData")
}
# https://datahub.io/core/s-and-p-500-companies
sp500Sectors = read.csv("constituents_csv.csv") %>% 
              mutate(sectorF = as.factor(Sector)) %>%
              mutate(sectorNumeric = as.numeric(sectorF))
```

```{r}
load("sp500-4year.RData")
```

```{r}
getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}
```

#DTW Clustering
```{r}
k=11
clusters = tsclust(returns %>% select(where(is.numeric)), k=k, distance="dtw_basic")
plot(clusters)

df = data.frame(stock = character(),
                cluster = factor(),
                sector = factor(),
                sector = character())
for (i in 1:length(clusters@cluster)) {
  stock = returns$symbol[i]
  row = c(stock, clusters@cluster[i], sp500Sectors[sp500Sectors$Symbol == stock,"sectorNumeric"], as.character(sp500Sectors[sp500Sectors$Symbol == stock,"sectorF"]))
  if(length(row) < 4) {
    row = c(row, "NA", "NA")
  }
  df = rbind(df, row)
}

colnames(df) = c("stock", "cluster", "sector", "sectorName")

# What does this do?
for(i in 1:k) {
  cat(df[df$sector == i,"sectorName"][1], " ",getmode(df[df$sector == i,"cluster"]), "\n")
}

# How many stocks are in each cluster
as.data.frame(table(clusters@cluster))
df[df$cluster == 1,]

#returns$symbol[which(clusters@cluster ==9)]
# https://rpubs.com/esobolewska/dtw-time-series
```

# Subset 
```{r}
start_date = '2020-01-03'
end_date = '2020-04-01'

dates = as.Date(colnames(returns)[-1], format = "%Y-%m-%d") #Get rid of first index which is the stock

stock_names = returns %>% select(1)
returns_subset =  returns %>%
    select((min(which(dates > start_date)) + 1):(max(which(dates < end_date) + 1)))


returns_subset = bind_cols(stock_names, returns_subset)

k=3
clusters = tsclust(returns_subset %>% select(where(is.numeric)), k=k, distance="dtw_basic")
plot(clusters)

df = data.frame(stock = character(),
                cluster = factor(),
                sector = factor(),
                sector = character())
for (i in 1:length(clusters@cluster)) {
  stock = returns$symbol[i]
  row = c(stock, clusters@cluster[i], sp500Sectors[sp500Sectors$Symbol == stock,"sectorNumeric"], as.character(sp500Sectors[sp500Sectors$Symbol == stock,"sectorF"]))
  if(length(row) < 4) {
    row = c(row, "NA", "NA")
  }
  df = rbind(df, row)
}

colnames(df) = c("stock", "cluster", "sector", "sectorName")
df[df$cluster == 1,]

```

#Kmeans

```{r clust}
kmeans.out = kmeans(clusters@distmat, centers=11)
heatmap(clusters@distmat, Colv=NA, Rowv=NA, scale="row")
```

# Elbow Method with KMeans
```{r}
plotW = rep(0,10)
for(K in 1:10){
plotW[K] = kmeans(clusters@distmat,centers=K,nstart=25)$tot.withinss
}
plot(plotW)
```

# CH Index With Kmeans

Both predict that 3 clusters is sufficient

```{r}
ch.index = function(x,kmax,iter.max=100,nstart=10, algorithm="Lloyd")
{
ch = numeric(length=kmax-1)
n = nrow(x)
for (k in 2:kmax) {
a = kmeans(x,k,iter.max=iter.max,nstart=nstart,
algorithm=algorithm)
w = a$tot.withinss
b = a$betweenss
ch[k-1] = (b/(k-1))/(w/(n-k))
}
return(list(k=2:kmax,ch=ch))
}

ch = ch.index(clusters@distmat, 15, nstart=25)
plot(ch$k, ch$ch, type="o")
```

```{r}
#https://jpiburn.github.io/fmpapi/
library(fmpapi)

api_key <- '7387eac0ea5783d3b57cfdb6e032c65a'
fmp_api_key(api_key)
readRenviron('~/.Renviron')

my_stocks = c('AAPL', 'BA')
key_metrics = fmp_key_metrics(my_stocks)
```
